name: assetsync
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  mysql1: ^0.20.0
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  http: ^0.13.5
  connectivity_plus: ^2.3.6+1
  crypto: ^3.0.2
  countup: ^0.1.4
  mailer: ^5.2.0
  geolocator: ^9.0.1
  geocoding: ^2.0.4
  flutter_map: ^2.2.0
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.5

  flutter_spinkit: ^5.1.0

  image_picker: ^0.8.5+3
  ftpconnect: ^1.0.1
  file_picker: ^5.0.1
  syncfusion_flutter_pdfviewer: ^20.2.45-beta
  

 

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/


  